# basic configuration goes here

url: "https://chackobabu.github.io/" 
# baseurl: ""
title: "CHACKO BABU" 
description: "Data Analyst"
email: "chacko.babu@protonmail.com"
theme: academic-jekyll-theme
port: 2233

markdown: kramdown
kramdown:
   math_engine: mathjax

