# basic configuration goes here

url: "https://chackobabu.github.io/" 
# baseurl: ""
title: "CHACKO BABU" 
description: "Data Analyst"
email: "chacko.babu@protonmail.com"
#theme: academic-jekyll-theme
port: 2233

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

markdown: kramdown
kramdown:
   math_engine: mathjax

