# basic configuration goes here

url: "https://chackobabu.github.io/" 
# baseurl: ""
title: "CHACKO BABU" 
description: "Development Researcher | Data Scientist"
email: "chacko.babu@protonmail.com"
theme: jekyll-theme-minimal
port: 2233

markdown: kramdown
kramdown:
   math_engine: mathjax

